# Generated by Django 6.0 on 2025-12-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuariopayway_reportepayway_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
    ]
