# Generated by Django 6.0 on 2025-12-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuariocdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVtex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='reportepayway',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15),
        ),
        migrations.CreateModel(
            name='TransaccionVtex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=100)),
                ('numero_transaccion', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('medio_pago', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.reportevtex')),
            ],
        ),
    ]
