# Generated by Django 6.0 on 2025-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reportevtex_alter_reportepayway_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioVtex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=200, verbose_name='API App Key')),
                ('app_token', models.CharField(max_length=500, verbose_name='API App Token')),
                ('account_name', models.CharField(default='carrefourar', max_length=100, verbose_name='Account Name')),
            ],
        ),
    ]
