# Generated by Django 4.2.27 on 2026-01-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_datos_iniciales_filtros_vtex'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncruce',
            name='resultado_cruce',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
