# Generated by Django 4.2.27 on 2026-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transaccioncruce_resultado_cruce'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionjanis',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
