# Generated by Django 4.2.27 on 2026-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_transaccionjanis_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncruce',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
