# Generated by Django 4.2.27 on 2026-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transaccioncruce_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevtex',
            name='incluir_sellers',
            field=models.BooleanField(default=True, help_text='Si está activo, busca el seller de cada pedido (proceso lento). Si está desactivado, el reporte se genera más rápido.', verbose_name='Incluir sellers'),
        ),
    ]
