# Generated by Django 4.2.27 on 2026-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_precios_to_transaccioncruce'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaCatalogacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BUSQUEDA_EANS', 'Busqueda EANs'), ('BUSQUEDA_CATEGORIAS', 'Busqueda Categorias'), ('SELLERS_EXTERNOS', 'Sellers Externos'), ('SELLERS_NO_CARREFOUR', 'Sellers No Carrefour'), ('ACTUALIZAR_MODAL', 'Actualizar Modal')], max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('logs', models.TextField(blank=True, default='')),
                ('progreso_actual', models.IntegerField(default=0)),
                ('progreso_total', models.IntegerField(default=0)),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='catalogacion/')),
            ],
            options={
                'verbose_name': 'Tarea de Catalogacion',
                'verbose_name_plural': 'Tareas de Catalogacion',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioCarrefourWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Usuario Carrefour Web',
                'verbose_name_plural': 'Usuarios Carrefour Web',
            },
        ),
    ]
